# Generated by Django 4.2.3 on 2023-07-26 17:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OTPAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
