# Generated by Django 4.2.3 on 2023-07-27 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OTPAuthApp', '0003_alter_profile_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
